INSERT INTO public.tb_event ("date", "location", "name", "organization", "address", "age", "tickets", "contact") VALUES('2023-11-16', 'HTL-Leonding', 'Birthday', 'Krenn', 'Limestraße 12', '16', 'siehe Instagram', 'siehe Instagram');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-03-11', 'Kürnberghalle', 'HTL-Ball', 'Kümmerer');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-05-06', 'Palais', 'Hornball 1', 'Tanzschule Horn');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-03-03', 'Tourismusschule BALE', 'Tourismusball', 'BALEonTour');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-05-01', 'Lichtenberg', 'Maifest', 'LJ');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-08-24', 'Palais', 'Hornball 2', 'Tanzschule Horn');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-05-05', 'Palais', 'Hornball 5', 'Tanzschule Horn');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-09-03', 'Tourismusschule ', 'Tourismusball', 'HBLA');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-11-01', 'Lichtenberg', 'Maifest', 'LJ');
INSERT INTO public.tb_event ("date", "location", "name", organization) VALUES('2024-08-24', 'Palais', 'Hornball 4', 'Tanzschule Horn');
